version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "dependabot"
    versioning-strategy: "auto"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      chakra:
        patterns:
          - "@chakra-ui/*"
      firebase:
        patterns:
          - "firebase"
          - "@firebase/*"
      eslint:
        patterns:
          - "eslint"
          - "@typescript-eslint/*"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 10
    automerge: true
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
